#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
export DISPLAY=":0"
export ECORE_IMF_MODULE="isf"
export ECORE_INPUT_FIX="1"
export ECORE_INPUT_TIMEOUT_FIX="0"
export EINA_LOG_DLOG_ENABLE="1"
export EINA_LOG_LEVEL="1"
export EINA_LOG_LEVELS="ecore_x:4,evas_main:1"
export EINA_LOG_SYSLOG_ENABLE="0"
export ELM_MODULES="ctxpopup_copypasteUI>entry/api:datetime_input_button>datetime/api:object_dump>win/api:access_output_tts>access/api"
export ELM_PROFILE="mobile"
export EVAS_FONT_DPI="72"
export EVAS_GL_NO_BLACKLIST="1"
export GTK_IM_MODULE="scim"
export GTK_IM_MODULE_FILE="/opt/etc/gtk-2.0/gtk.immodules"
export HIB="a"
export HISTSIZE="1000"
export HOME="/root"
export HUSHLOGIN="FALSE"
export LD_LIBRARY_PATH=":/usr/lib:/usr/lib/driver"
export LOGNAME="root"
export MULTISENSE_SND_PLAYER="tizen_snd_player"
export OLDPWD
export PATH="/usr/share/scripts:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/usr/devel/usr/sbin:/opt/usr/devel/usr/bin:/opt/usr/devel/sbin:/opt/usr/devel/bin"
export SCIM_MODULE_PATH="/opt/apps/scim/lib/scim-1.0"
export SHELL="/bin/sh"
export SHLVL="2"
export TERM="vt102"
export USER="root"
export XDG_CACHE_HOME="/tmp/.cache"
export XMODIFIERS="@im=SCIM"

$DIR/keyscan /dev/event0 /dev/event1 $DIR

